import random


class Card:
    def __init__(self):
        self.__cards: [str] = [
            "R1",
            "R2",
            "R3",
            "R4",
            "R5",
            "R6",
            "R7",
            "R8",
            "R9",
            "Y1",
            "Y2",
            "Y3",
            "Y4",
            "Y5",
            "Y6",
            "Y7",
            "Y8",
            "Y9",
            "G1",
            "G2",
            "G3",
            "G4",
            "G5",
            "G6",
            "G7",
            "G8",
            "G9",
            "B1",
            "B2",
            "B3",
            "B4",
            "B5",
            "B6",
            "B7",
            "B8",
            "B9",
            "RA",
            "YA",
            "GA",
            "BA",
            "RJ",
            "YJ",
            "GJ",
            "BJ",
            "RU",
            "YU",
            "GU",
            "BU",
            "R1",
            "R2",
            "R3",
            "R4",
            "R5",
            "R6",
            "R7",
            "R8",
            "R9",
            "Y1",
            "Y2",
            "Y3",
            "Y4",
            "Y5",
            "Y6",
            "Y7",
            "Y8",
            "Y9",
            "G1",
            "G2",
            "G3",
            "G4",
            "G5",
            "G6",
            "G7",
            "G8",
            "G9",
            "B1",
            "B2",
            "B3",
            "B4",
            "B5",
            "B6",
            "B7",
            "B8",
            "B9",
            "RA",
            "YA",
            "GA",
            "BA",
            "RJ",
            "YJ",
            "GJ",
            "BJ",
            "RU",
            "YU",
            "GU",
            "BU",
            "RP",
            "YP",
            "GP",
            "BP",
        ]
        self.__dummy: [str] = []

    def setup(self):
        random.shuffle(self.__cards)
        self.__dummy = self.__cards.copy()

    def get_from_dummy(self, num_card: int) -> [str]:
        cards: [str] = []
        for _ in range(num_card):
            cards.append(self.__dummy.pop())
        return cards

    def add_to_dummy(self, card: str):
        self.__dummy.insert(0, card)
